### PR TITLE
Handle transformation of fields containing arrays of arrays

### PR DESCRIPTION
**Pull request by andresloal**
There was a problem when trying to transform a JSON file containing fields with arrays of arrays, like this little example:
```
{
  "arrayOfArrays": [
    [
      "foo",
      "bar",
      "extra"
    ],
    [
      "blue",
      "red",
      "yellow"
    ]
  ]
}
```
Returns a schema like:
```
type ArrayOfArrays [String ]
type AutogeneratedMainType { arrayOfArrays: [ArrayOfArrays ] }
```
Which generates an error when trying to use the schema, the accepted GraphQL syntax is:
```
type AutogeneratedMainType { arrayOfArrays: [[String]] }
```
Few codes added to deal with these cases.

### CODE REVIEW

**Comment by maxnachlinger** [comment]
Thanks for the PR! Please fix up the formatting (you can run `npm run format`) an add a test for this case.

**Comment by andresloal** [comment]
Sorry, I'm a newbie at GitHub and I had problems to run the format and the test because I use Windows, hope it will be helpful!

**Comment by maxnachlinger** [comment]
@andresloal would you mind signing the Contributor License Agreement? I'll then be happy to merge your PR.

**Comment by andresloal** [comment]
No problem, I already read and signed the agreement

**Pull request merged**
